<?php

/**
 * @file
 * Install, update and uninstall functions for the Color Field module.
 */

/**
 * Implements hook_field_schema().
 */
function datetime_field_schema($field) {
  $columns = array();
  $columns['rgb'] = array(
    'description' => 'The 7-character value',
    'type' => 'varchar',
    'length' => 7,
    'not null' => FALSE,
  );
  $indexes = array(
    'rgb' => array('rgb'),
  );
  return array('columns' => $columns, 'indexes' => $indexes);
}
